Added more documentation
gosub-browser/gosub-engine pull request #127
Opened 2023-10-10 17:16 UTC by jaytaph

2023-10-10 17:38 UTC, blaumeise20 requested changes
I have no idea if I'm "socially" allowed to review stuff in here, but I have one suggestion: don't use a "This blabla" style but a more present ... way (I forgot the name). So instead of writing
```
This module contains the HTML5 parser as specified by the W3C.
```
I would write
```
The HTML5 parser implemented according to the W3C specification.
```
Similar things apply for some other things like macros and structs. Essentially it should be consistent with the way methods/functions are documented, e.g.:
```
Returns the current offset in the stream
```

2023-10-10 17:58 UTC, jaytaph commented
> I have no idea if I'm "socially" allowed to review stuff in here

everyone is :-)

I think it is a good idea. If you willing to help us out on this, that would be even better :)

2023-10-10 23:50 UTC, emwalker commented
> I have no idea if I'm "socially" allowed to review stuff in here

That's how we all got here so far. :)

2023-10-11 00:03 UTC, emwalker commented on src/api.rs
> +//! This module contains all the APIs that are exposed through javascript
```suggestion
//! All the APIs that are exposed through JavaScript
```

Just to run with @blaumeise20's thought.  He might have additional suggestions.

2023-10-11 00:03 UTC, emwalker commented on src/api/console.rs
> +//! This module contains the console api as described by <https://console.spec.whatwg.org/>
```suggestion
//! The console API, as described by <https://console.spec.whatwg.org/>
```

2023-10-11 00:03 UTC, emwalker commented on src/html5_parser.rs
> +//! This module contains the HTML5 parser as specified by the W3C.
```suggestion
//! The HTML5 parser, following the W3C specification
```

2023-10-11 00:03 UTC, emwalker commented on src/html5_parser/input_stream.rs
> +    /// Returns true when the element is an EOF
```suggestion
    /// Whether the element is an EOF
```

You get the idea.  Similar suggestions apply further down.

2023-10-11 13:19 UTC, Kiyoshika approved these changes

2023-10-11 14:24 UTC, jaytaph commented
Lets merge as-is, and change later when we have something more formalized

2023-10-11 14:24 UTC, merged